language: go
go:
  - 1.12.x
  - 1.13.x
  - master
os:
  - linux
  - freebsd
  - osx
  - windows
before_install:
  - go get github.com/mattn/goveralls
notifications:
  email:
    recipients:
      - johnkenneth.moore@gmail.com
    on_success: never
    on_failure: always 
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
